server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
          - Path=/payment/lb/** #断言,路径相匹配的进行路由
#          时间级别
#          - After=2020-10-16T10:40:30.256+08:00[Asia/Shanghai]
#          - Before=2020-10-16T10:40:30.256+08:00[Asia/Shanghai]
#          - Between=2020-10-16T09:40:30.256+08:00[Asia/Shanghai],2020-10-16T10:40:30.256+08:00[Asia/Shanghai]
#          - Cookie=username,dhc    #带Cookie，并且username的值为eiletxie
#          - Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
#          - Host=**.atguigu.com
#          - Method=GET
#          - Query=username, \d+ #要有参数名称并且是正整数才能路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/